version: 3
includes:
  core: .task/core/
env:
  VERSION: "0.0.0"
vars:
  PROJECT: '{{ .PROJECT | default "my-project" }}'
tasks:
  init:
    - task: core:init
    - task: init:python
  init:python:
    desc: Install required application dependencies
    sources:
      - requirements.txt
    cmds:
      - pip3 install -r requirements.txt

  start:
    desc: Bootstrap the server and load from config
    deps: [init:python]
    cmds:
      - ./main.py --debug

  update: [{ task: "core:update" }]
  clean: [{ task: "core:clean" }]

  # -------------------------------------------------
  # Example commands
  # -------------------------------------------------
  example:alpha:
    desc: Testing
    sources:
      - Taskfile.yaml
    generates:
      - "./dist/lala.txt"
    cmds:
      - mkdir -p ./dist
      - cat Taskfile.yaml > ./dist/lala.txt
      - sleep 3

  example:beta:
    vars:
      MESSAGE: Hello World
      OUTPUT_PATH: ./some/path
    cmds:
      - echo "{{ .MESSAGE }}"
      - task: example
      - echo {{ .OUTPUT_PATH }}

  example:omega:
    - echo "Updating sources..."
    - task: update
    - echo "Start Examples..."
    - task: example
    - task: example2
    - echo "Done"
