version: 3
includes:
  core: .task/core/
env:
  VERSION: "0.0.0"
vars:
  PROJECT: '{{ .PROJECT | default "my-project" }}'
tasks:
  init:
    - task: core:init
    - task: init:python
  init:python:
    desc: Install required application dependencies
    sources:
      - requirements.txt
    cmds:
      - pip3 install -r requirements.txt

  start:
    desc: Bootstrap the server and load from config
    deps: [init:python]
    cmds:
      - ./main.py --debug

  update: [{ task: "core:update" }]
  clean: [{ task: "core:clean" }]

  # -------------------------------------------------
  # Example commands
  # -------------------------------------------------
  example:
    desc: A fairly complex example task
    vars:
      MESSAGE: '{{ .MESSAGE | default "Hello World" }}'
      OUTPUT_PATH: ./dist/lala.txt
    cmds:
      - echo "{{ .MESSAGE }}"
      - task: example:alpha
      - task: example:beta
      - task: example:omega
      - echo Done
  example:alpha:
    desc: First example task
    sources:
      - Taskfile.yaml
    generates:
      - "./dist/lala.txt"
    cmds:
      - mkdir -p ./dist
      - cat Taskfile.yaml > ./dist/lala.txt      
  example:beta:
    desc: Second example task
    cmds:
      - sleep 1
  example:fail:
    desc: Explicitly exit with exit status
    cmds:
      - echo "Crashing this task..." 1>&2
      - exit 2
  example:infinite:
    desc: Run this task indefinately
    cmds:
      - echo "Starting infinite loop"
      - |-
        count=1
        while true; 
        do 
          echo $count
          sleep 2
          count=$(( $count + 1 ))
        done

  example:omega:
    - echo "Updating sources..."
    - task: update
    - sleep 1
    - echo "Done"
